In [19]:
import numpy as np
features = ['Bedrooms', 'Bathrooms', 'Square Feet']
house_0 = np.array([[3, 3, 3000]])
house_1 = np.array([[3, 2, 2500]])
house_2 = np.array([[4, 3, 3200]])
house_x = np.array([[4, 4, 3100]])
X = np.vstack([house_0,house_1,house_2])
X

array([[   3,    3, 3000],
       [   3,    2, 2500],
       [   4,    3, 3200]])

In [20]:
prices = np.array([[350000, 300000, 425000]]).T
prices

array([[350000],
       [300000],
       [425000]])

# (X) * (Weights) = Prices
# (X_inv)*(X)*(Weights) = (X_inv)*(Prices)
# I*(Weights) = (X_inv)*(Prices)
# Weights = (X_inv)*(Prices)

In [21]:
Weights = np.linalg.inv(X).dot(prices)
Weights

array([[ 8.05555556e+04],
       [ 6.38888889e+04],
       [-2.77777778e+01]])

In [22]:
for feature, weight in zip(features, Weights):
    print('Keeping all other factors equal, each 1-unit increase in {} raises the prices by {}'.format(feature,weight))

Keeping all other factors equal, each 1-unit increase in Bedrooms raises the prices by [80555.55555556]
Keeping all other factors equal, each 1-unit increase in Bathrooms raises the prices by [63888.88888889]
Keeping all other factors equal, each 1-unit increase in Square Feet raises the prices by [-27.77777778]


In [23]:
print('The predicted prices of House_x is: ')
print(house_x.dot(Weights))

The predicted prices of House_x is: 
[[491666.66666667]]
